config/routes.rb
Rails.application.routes.draw do
  resources :todos
  resources :users

  get '/about', to: 'pages#about'
  get '/help',  to: 'pages#help'

  get '/signup',    to: 'users#new'

  get '/login',     to: 'sessions#new'
  post '/login',    to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  root 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :user

  validates :name, length: { minimum: 5 }
  validates :description, length: { minimum: 12 }
  validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }

  has_secure_password

  has_many :todos, dependent: :destroy

  # A verrry minimal EMAIL Regex
  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  validates :name, presence: true, length: { in: 5..60 }
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true  # allow nil only actions on edit
  validates :email,
    presence:   true,
    length:     { minimum: 8 },
    format:     { with: EMAIL_REGEX },
    uniqueness: { case_sensitive: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current ||= User.find session[:user_id] if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    unless logged_in?
      flash[:danger] = "You must be logged in to do that"
      redirect_to root_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home

  end

  def about

  end

  def help

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user = User.find_by email: session_params[:email].downcase

    if user && user.authenticate(session_params[:password])
      session[:user_id] = user.id
      flash[:success] = "You have logged in successfully"
      redirect_to user
    else
      flash[:danger] = "We didn't recognise that email and password"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have logged out successfully"
    redirect_to root_path
  end

  private

  def session_params
    params.require(:session).permit :email, :password
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @todos = Todo.all
  end

  def show

  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new todo_params
    @todo.user = current_user

    if @todo.save
      flash[:notice] = 'The new task was saved successfully'
      redirect_to @todo
    else
      flash.now[:error] = 'The task could not be saved'
      render :new
    end
  end

  def edit

  end

  def update
    if @todo.update todo_params
      flash[:notice] = 'The task was updated successfully'
      redirect_to @todo
    else
      flash.now[:error] = 'The task could not be updated'
      render :edit
    end
  end

  def destroy
    if @todo.destroy
      flash[:notice] = 'The task was deleted successfully'
      redirect_to todos_path
    else
      flash.now[:error] = 'The task could not be updated'
      redirect_back
    end
  end

  private

  def todo_params
    params.require(:todo).permit :name, :description
  end

  def set_todo
    @todo = Todo.find params[:id]
  end

  def require_same_user
    unless current_user == @todo.user || current_user.admin?
      flash[:danger] = 'You can only edit and delete your own tasks'
      redirect_to todos_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show

  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params

    if @user.save
      flash[:success] = "You have signed up successfully"
      redirect_to @user
    else
      render :new
    end
  end

  def edit

  end

  def update
    if @user.update user_params
      flash[:success] = "You have updated your profile successfully"
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    flash[:success] = "The user and their tasks have been deleted successfully"
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit :name, :email, :password, :password_confirmation
  end

  def set_user
    @user = User.find params[:id]
  end

  def require_same_user
    unless current_user == @user || current_user.admin?
      flash[:danger] = 'You can only edit and delete your own account'
      redirect_to users_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_header.html.erb
<header>
  <ul>
    <li class="brand"><%= link_to 'Agenda', root_path %></li>
    <li><%= link_to 'Users', users_path %></li>
    <li><%= link_to 'Tasks', todos_path %></li>

    <% if logged_in? %>
      <li><%= link_to 'New Task', new_todo_path %></li>
      
      <li class="pull-right"><%= link_to 'Log out', logout_path, method: :delete %></li>
      <li class="pull-right"><%= link_to 'Edit Profile', edit_user_path(current_user) %></li>
    <% else %>
      <li class="pull-right"><%= link_to 'Sign up', signup_path %></li>
      <li class="pull-right"><%= link_to 'Log in', login_path %></li>
    <% end %>
  </ul>
</header>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name %>">
    <%= msg %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA_Compatible" content="IE=edge">

    <title>Agenda Task App</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://use.fontawesome.com/3d3a1ab939.js"></script>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/messages' %>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1 class="text-center">About the Agenda App</h1>

<p>About this app.</p>

<%= link_to 'Home', root_path %>

app/views/pages/help.html.erb
<h1 class="text-center">Help!</h1>

<img src="/images/help.jpg" alt="">

<%= link_to 'Home', root_path %>

app/views/pages/home.html.erb
<h1 class="text-center">Agenda</h1>

<p>Far far away, behind the word mountains, far from the countries Vokalia and
Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right
at the coast of the Semantics, a large language ocean. A small river named Duden
flows by their place and supplies it with the necessary regelialia.</p>

<p>It is a paradisematic country, in which roasted parts of sentences fly into your
mouth. Even the all-powerful Pointing has no control about the blind texts it is an
almost unorthographic life One day however a small line of blind text by the name of
Lorem Ipsum decided to leave for the far World of Grammar.</p>

<p>The Big Oxmox advised her not to do so, because there were thousands of bad
Commas, wild Question Marks and devious Semikoli, but the Little Blind Text didn’t
listen. She packed her seven versalia, put her initial into the belt and made herself
on the way. When she reached the first hills of the Italic Mountains, she had a last
view back on the skyline of her hometown Bookmarksgrove, the headline of Alphabet
Village and the subline of her own road, the Line Lane. Pityful a rethoric question
ran over her cheek, then</p>

<%= link_to 'About', about_path %> |
<%= link_to 'Help', help_path %>

app/views/todos/_form.html.erb
<% if @todo.errors.any? %>
  <div class="errors">
    <h4>The task could not be saved due to <%= pluralize(@todo.errors.count, 'error') %>:</h4>
    <ol>
    <% @todo.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ol>
  </div>
<% end %>

<%= form_for @todo do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name, placeholder: 'What do you need to do?', autofocus: true %>
  </p>

  <p>
    <%= f.label :description %>
    <%= f.text_area :description, rows: 10, placeholder: 'How are you going to perform this task?' %>
  </p>

  <%= f.submit (@todo.new_record? ? 'Add Task' : 'Update Task'), class: 'btn' %>
<% end %>

app/views/todos/edit.html.erb
<h1 class="text-center">Edit Task</h1>

<%= render 'form' %>

<p class="text-center">
  [ <%= link_to 'Back to Task List', todos_path %> ]
</p>

app/views/todos/index.html.erb
<h1 class="text-center">Tasks</h1>

<% @todos.each do |task| %>
  <article>
    <h2 class="text-center">
      <%= link_to "#{task.name}", task %> - <small><%= task.user.name %></small>
    </h2>

    <p><%= truncate(task.description, length: 150) %></p>

    <% if logged_in? && (current_user == task.user || current_user.admin?) %>
      <div class="actions">
        <%= link_to 'Edit', edit_todo_path(task), class: 'btn' %>
        <%= link_to 'Delete', task, class: 'btn', method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>
  </article>
<% end %>

<p><%= link_to 'New Task', new_todo_path, class: 'btn' %></p>

app/views/todos/new.html.erb
<h1 class="text-center">Add a Task</h1>

<%= render 'form' %>

app/views/todos/show.html.erb
<h1><%= @todo.name %></h1>

<article>
  <%= simple_format(@todo.description) %>
</article>

<% if logged_in? && (current_user == @todo.user || current_user.admin?) %>
  <p class="actions">
    <%= link_to 'Edit', edit_todo_path(@todo), class: 'btn' %>
    <%= link_to 'Delete', @todo, class: 'btn', method: :delete, data: { confirm: 'Are you sure?' } %>
  </p>
<% end %>

<p>
  <%= link_to 'Back to Task List', todos_path, class: 'btn' %>
</p>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <div class="errors">
    <h4>The user could not be saved due to <%= pluralize(@user.errors.count, 'error') %>:</h4>
    <ol>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ol>
  </div>
<% end %>

<%= form_for @user do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name, placeholder: 'Enter your name', autofocus: true %>
  </p>

  <p>
    <%= f.label :email %>
    <%= f.email_field :email, placeholder: 'Enter your email address' %>
  </p>

  <p>
    <%= f.label :password %>
    <%= f.password_field :password, placeholder: 'Choose a password (min 6 characters)' %>
  </p>

  <p>
    <%= f.label :password_confirmation, 'Confirm Password' %>
    <%= f.password_field :password_confirmation, placeholder: 'Re-enter the password' %>
  </p>

  <%= f.submit (@user.new_record? ? 'Sign up' : 'Save Changes'), class: 'btn' %>
<% end %>

app/views/users/edit.html.erb
<h1 class="text-center">Edit your Profile</h1>

<%= render 'form' %>

<p class="text-center">
  [ <%= link_to 'Return to Profile', @user %> ]
</p>

app/views/users/index.html.erb
<h1 class="text-center">All Users</h1>

<% @users.each do |user| %>
  <article>
    <h2><%= link_to user.name, user %></h2>
    <p>Email Address: <%= user.email %></p>
    <p><%= pluralize user.todos.count, 'task' %></p>

    <% if logged_in? && (current_user == user || current_user.admin?) %>
      <div class="actions">
        <%= link_to 'Edit', edit_user_path(user), class: 'btn' %>
        <%= link_to 'Delete', user, class: 'btn', method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>
  </article>
<% end %>

app/views/users/new.html.erb
<h1 class="text-center">Sign up for Agenda</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="text-center"><%= @user.name %></h1>

<p class="text-center">Email Address: <%= @user.email %></p>

<% if logged_in? && (current_user == @user || current_user.admin?) %>
  <p><%= link_to 'Edit Profile', edit_user_path(@user), class: 'btn' %></p>
<% end %>

<p>
  <%= link_to 'Back to User List', users_path, class: 'btn' %>
</p>